name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Wheel (${{ matrix.python-tag }}-${{ matrix.platform }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-2019 ]
        python-tag: [ "cp39", "cp310", "cp311", "cp312", "cp313" ]
        include:
          - os: ubuntu-latest
            platform: manylinux_x86_64
          - os: windows-2019
            platform: win_amd64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86_64

      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.0
        env:
          CIBW_BUILD: ${{ matrix.python-tag }}-${{ matrix.platform }}
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: papi-${{ matrix.python-tag }}-${{ matrix.platform }}
          path: ./wheelhouse/*.whl